version: "3.4"

networks:
  permissionsNetwork:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - permissionsNetwork

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - permissionsNetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desactiva autenticación
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - permissionsNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - permissionsNetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - permissionsNetwork

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  elasticsearch_data:
    driver: local
  sqlserver_data:
    driver: local
