@PermissionsApp.Command.Api_HostAddress = http://localhost:5112

POST {{PermissionsApp.Command.Api_HostAddress}}/api/Permission/create
Content-Type: application/json
Accept: application/json

{
  "employeeName": "Test7",
  "employeeLastName": "Test5",
  "permissionDate": "2025-10-26T10:00:00",
  "permissionTypeId": 4
}

###

DELETE {{PermissionsApp.Command.Api_HostAddress}}/api/Permission/6
Content-Type: application/json
Accept: application/json

###

PUT {{PermissionsApp.Command.Api_HostAddress}}/api/Permission/7
Content-Type: application/json
Accept: application/json

{
  "employeeName": "Sergio",
  "employeeLastName": "Rondon2",
  "permissionDate": "2026-01-26T10:00:00",
  "permissionTypeId": 3
}

###
