@PermissionsApp.Command.Api_HostAddress = http://localhost:5112

POST {{PermissionsApp.Command.Api_HostAddress}}/api/Permission/
Content-Type: application/json
Accept: application/json

{
  "employerName": "Sergio",
  "employerLastName": "Rondon",
  "permissionDate": "2024-01-26T10:00:00",
  "permissionId": 5
}

###
